import { existsSync, readFileSync } from "node:fs";

const required = [
  ".oworker/project.json",
  ".oworker/starter.json",
  ".env.example",
  ".env.development",
  "AGENTS.md",
  "DESIGN.md",
  "delivery/README.md",
  "docs/anss-v0.1.md",
  "docs/site-admin.md",
  ".dockerignore",
  ".agents/skills/project-maintenance/SKILL.md",
  ".agents/skills/application-maintenance/SKILL.md",
  ".agents/skills/saas-maintenance/SKILL.md",
  "interfaces/openapi/openapi.yaml",
  "interfaces/openapi/saas.openapi.yaml",
  "interfaces/service-map/README.md",
  "interfaces/service-map/saas.service-map.json",
  "interfaces/service-map/saas.service-map.yaml",
  "interfaces/aclip/README.md",
  "interfaces/aclip/saas.md",
  "interfaces/mcp/saas.md",
  "interfaces/skills/saas-auth.md",
  "interfaces/skills/anss-service.md",
  "interfaces/skills/account-console.md",
  "interfaces/skills/site-admin.md",
  "integration/saas.md",
  "ops/docker/compose.yaml",
  "pnpm-workspace.yaml",
  "scripts/docker-compose.mjs",
  "scripts/smoke.mjs",
  "scripts/doctor-production.mjs",
  "scripts/sync-anss-service-map.mjs",
  "scripts/anss-conformance.mjs",
  "scripts/anss-agent-probe.mjs",
  "turbo.json",
  "src/apps/api/Dockerfile",
  "src/apps/api/package.json",
  "src/apps/api/scripts/migrate.mjs",
  "src/apps/api/src/capabilities.mjs",
  "src/apps/api/src/server.mjs",
  "src/apps/cli/package.json",
  "src/apps/cli/src/cli.mjs",
  "src/apps/mcp/README.md",
  "src/apps/mcp/src/server.mjs",
  "src/apps/worker/Dockerfile",
  "src/apps/worker/README.md",
  "src/apps/worker/src/worker.mjs",
  "src/apps/web/app/api/auth/[...all]/route.ts",
  "src/apps/web/app/api/account/profile/route.ts",
  "src/apps/web/app/api/account/set-password/route.ts",
  "src/apps/web/app/api/account/avatar/upload/route.ts",
  "src/apps/web/app/api/account/avatar/confirm/route.ts",
  "src/apps/web/app/api/account/avatar/image/route.ts",
  "src/apps/web/app/api/email-verification/send/route.ts",
  "src/apps/web/app/api/billing/checkout/route.ts",
  "src/apps/web/app/api/billing/portal/route.ts",
  "src/apps/web/app/api/billing/webhook/route.ts",
  "src/apps/web/app/api/analytics/event/route.ts",
  "src/apps/web/app/api/anss/manifest/route.ts",
  "src/apps/web/app/mcp/route.ts",
  "src/apps/web/app/api/locale/route.ts",
  "src/apps/web/public/agent-guide.md",
  "src/apps/web/public/llms.txt",
  "src/apps/web/public/anss/saas.service-map.yaml",
  "src/apps/web/public/anss/openapi/saas.openapi.yaml",
  "src/apps/web/public/anss/install/index.json",
  "src/apps/web/public/anss/install/cli.json",
  "src/apps/web/public/anss/install/mcp.json",
  "src/apps/web/public/anss/install/skills.json",
  "src/apps/web/public/anss/install/openapi.json",
  "src/apps/web/app/(public)/page.tsx",
  "src/apps/web/app/(public)/pricing/page.tsx",
  "src/apps/web/app/(account)/account/page.tsx",
  "src/apps/web/app/(account)/account/billing/page.tsx",
  "src/apps/web/app/(admin)/admin/layout.tsx",
  "src/apps/web/app/(admin)/admin/page.tsx",
  "src/apps/web/app/(admin)/admin/users/page.tsx",
  "src/apps/web/app/(admin)/admin/revenue/page.tsx",
  "src/apps/web/app/(admin)/admin/subscriptions/page.tsx",
  "src/apps/web/app/(admin)/admin/analytics/page.tsx",
  "src/apps/web/app/(admin)/admin/health/page.tsx",
  "src/apps/web/app/(admin)/admin/audit-logs/page.tsx",
  "src/apps/web/app/(admin)/admin/diagnostics/page.tsx",
  "src/apps/web/app/(auth)/layout.tsx",
  "src/apps/web/app/(auth)/forgot-password/page.tsx",
  "src/apps/web/components/admin-nav.tsx",
  "src/apps/web/components/auth-card.tsx",
  "src/apps/web/components/site-header.tsx",
  "src/apps/web/components/user-menu.tsx",
  "src/apps/web/components/user-menu-dropdown.tsx",
  "src/apps/web/components/command-copy.tsx",
  "src/apps/web/components/pricing-plans.tsx",
  "src/apps/web/components/account-verification-form.tsx",
  "src/apps/web/components/account-profile-card.tsx",
  "src/apps/web/components/account-security-forms.tsx",
  "src/apps/web/components/i18n-provider.tsx",
  "src/apps/web/components/connected-accounts-panel.tsx",
  "src/apps/web/components/language-switcher.tsx",
  "src/apps/web/components/oauth-buttons.tsx",
  "src/apps/web/components/password-reset-request-form.tsx",
  "src/apps/web/components/public-content-shell.tsx",
  "src/apps/web/components/reset-password-form.tsx",
  "src/apps/web/components/status-alert.tsx",
  "src/apps/web/components/status-badge.tsx",
  "src/apps/web/components/theme-provider.tsx",
  "src/apps/web/components/theme-toggle.tsx",
  "src/apps/web/.env.example",
  "src/apps/web/.env.development",
  "src/apps/web/hooks/use-mobile.ts",
  "src/apps/web/emails/email-change-confirmation-email.tsx",
  "src/apps/web/emails/password-reset-email.tsx",
  "src/apps/web/emails/verification-email.tsx",
  "src/apps/web/i18n/config.ts",
  "src/apps/web/i18n/messages.ts",
  "src/apps/web/i18n/server.ts",
  "src/apps/web/app/(auth)/login/page.tsx",
  "src/apps/web/app/(public)/privacy/page.tsx",
  "src/apps/web/app/(public)/support/page.tsx",
  "src/apps/web/app/(public)/terms/page.tsx",
  "src/apps/web/app/(auth)/verify-email/page.tsx",
  "src/apps/web/components/verify-email-panel.tsx",
  "src/apps/web/messages/en.json",
  "src/apps/web/messages/zh-CN.json",
  "src/apps/web/app/(auth)/register/page.tsx",
  "src/apps/web/app/(auth)/reset-password/page.tsx",
  "src/apps/web/lib/auth.ts",
  "src/apps/web/lib/account.ts",
  "src/apps/web/lib/admin.ts",
  "src/apps/web/lib/analytics.ts",
  "src/apps/web/lib/avatar-storage.ts",
  "src/apps/web/lib/audit.ts",
  "src/apps/web/lib/billing.ts",
  "src/apps/web/lib/email.ts",
  "src/apps/web/lib/email-verification.ts",
  "src/apps/web/lib/oauth.ts",
  "src/apps/web/lib/urls.ts",
  "src/apps/web/lib/saas-console.ts",
  "src/apps/web/scripts/migrate-auth.mjs",
  "src/packages/application/README.md",
  "src/packages/application/src/index.ts",
  "src/packages/auth/README.md",
  "src/packages/cache/README.md",
  "src/packages/cache/src/index.ts",
  "src/packages/db/README.md",
  "src/packages/billing/README.md",
  "src/packages/billing/src/index.ts",
  "src/packages/storage/README.md",
  "src/packages/storage/src/index.ts",
  "src/packages/email/README.md",
  "src/packages/email/src/index.ts",
  "src/packages/observability/README.md",
  "src/packages/observability/src/logger.ts",
  "src/packages/queue/README.md",
  "src/packages/queue/src/index.ts",
  "src/features/auth/README.md",
  "src/providers/auth/README.md",
  "src/providers/billing/README.md",
  "src/providers/cache/README.md",
  "src/providers/database/README.md",
  "src/providers/email/README.md",
  "src/providers/i18n/README.md",
  "src/providers/observability/README.md",
  "src/providers/queue/README.md",
  "src/providers/storage/README.md",
  "tests/contracts/saas-auth.README.md"
];

const shadcnComponents = [
  "accordion",
  "alert-dialog",
  "alert",
  "aspect-ratio",
  "avatar",
  "badge",
  "breadcrumb",
  "button-group",
  "button",
  "calendar",
  "card",
  "carousel",
  "chart",
  "checkbox",
  "collapsible",
  "combobox",
  "command",
  "context-menu",
  "dialog",
  "direction",
  "drawer",
  "dropdown-menu",
  "empty",
  "field",
  "hover-card",
  "input-group",
  "input-otp",
  "input",
  "item",
  "kbd",
  "label",
  "menubar",
  "native-select",
  "navigation-menu",
  "pagination",
  "popover",
  "progress",
  "radio-group",
  "resizable",
  "scroll-area",
  "select",
  "separator",
  "sheet",
  "sidebar",
  "skeleton",
  "slider",
  "sonner",
  "spinner",
  "switch",
  "table",
  "tabs",
  "textarea",
  "toggle-group",
  "toggle",
  "tooltip"
];

required.push(...shadcnComponents.map((name) => `src/apps/web/components/ui/${name}.tsx`));

const lockOrManifest = readJsonIfExists(".oworker/starter.lock.json") || readJsonIfExists(".oworker/manifest.json") || {};
const capabilities = new Set(Array.isArray(lockOrManifest.capabilities) ? lockOrManifest.capabilities : []);

if (capabilities.has("db:drizzle")) {
  required.push(
    "src/packages/db/migrations/0001_initial.sql",
    "src/packages/db/src/schema.ts"
  );
}

const missing = required.filter((path) => !existsSync(path));
const forbidden = [
  "src/apps/api/package-lock.json",
  "src/apps/worker/package-lock.json"
].filter((path) => existsSync(path));

if (missing.length > 0 || forbidden.length > 0) {
  console.error("Missing required OWorker SaaS Starter files:");
  for (const path of missing) {
    console.error(`- ${path}`);
  }
  for (const path of forbidden) {
    console.error(`- forbidden: ${path}`);
  }
  process.exitCode = 1;
} else {
  console.log("OWorker SaaS Starter health check passed.");
}

function readJsonIfExists(path) {
  if (!existsSync(path)) {
    return null;
  }
  return JSON.parse(readFileSync(path, "utf8"));
}
